@portfolio_api_HostAddress = http://localhost:5248

### Obter perfil de usuário por ID

GET {{portfolio_api_HostAddress}}/api/profile/2
Accept: application/json

### Obter perfis de usuário

GET {{portfolio_api_HostAddress}}/api/profile/
Accept: application/json

### Criar perfil de usuário

POST {{portfolio_api_HostAddress}}/api/profile/
Content-Type: application/json

{
    "name": "John Doe",
    "aboutMe": "I am a software developer"
}

### Conectar ou desconectar perfil de usuário a uma rede social 

POST {{portfolio_api_HostAddress}}/api/profile/1/social-media
Content-Type: application/json

# kind: connect or disconnect

{
    "socialMediaID": 1,
    "kind":"connect" 
}

### Atualizar perfil de usuário

PATCH {{portfolio_api_HostAddress}}/api/profile/3
Content-Type: application/json

{
    "name":"João Duim"
}

### Apagar perfil de usuário

DELETE {{portfolio_api_HostAddress}}/api/profile/2
Accept: application/json

### Obter redes sociais

GET {{portfolio_api_HostAddress}}/api/social-media/
Accept: application/json

### Obter redes sociais por id

GET {{portfolio_api_HostAddress}}/api/social-media/1
Accept: application/json

### Criar rede social

POST {{portfolio_api_HostAddress}}/api/social-media
Content-Type: application/json

# name: Nome da rede social (SocialMediaNames enum)

{
    "name":"Github",
    "url":"https://github.com",
    "profileID": 3
}

### Atualizar rede social

PATCH {{portfolio_api_HostAddress}}/api/social-media/3
Content-Type: application/json

{
    "name":"Linkedin",
    "url":"https://linkedin.com",
    "profileID": 1
}

### Deletar rede social

DELETE {{portfolio_api_HostAddress}}/api/social-media/2
Accept: application/json